AWSTemplateFormatVersion: 2010-09-09
Description: Fetching data from sources
Transform: AWS::Serverless-2016-10-31

Parameters:
  EnvironmentName:
    Description: Environment name
    Type: String

  LoggingLevel:
    Description: Logging level
    Type: String

  S3BucketName:
    Description: S3 Bucket name to store data
    Type: String

Resources:
  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub ${EnvironmentName}-sns-topic

  UKSourceStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: SNSTopic
    Properties:
      TemplateURL: ./fetching_data_from_source.yaml
      Parameters:
        EnvironmentName: !Sub ${EnvironmentName}
        DataSourceName: uk_source
        SNSTopicARN: !Ref SNSTopic
        LoggingLevel: !Sub ${LoggingLevel}
        S3BucketName: !Sub ${S3BucketName}
        LambdaCode: ./lambda/uk_data_consumer

  USASourceStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: SNSTopic
    Properties:
      TemplateURL: ./fetching_data_from_source.yaml
      Parameters:
        EnvironmentName: !Sub ${EnvironmentName}
        DataSourceName: usa_source
        SNSTopicARN: !Ref SNSTopic
        LoggingLevel: !Sub ${LoggingLevel}
        S3BucketName: !Sub ${S3BucketName}
        LambdaCode: ./lambda/usa_data_consumer
